#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SEO QA — anti-regression suite for stp-terrassement.com (SEO spec v2, T-40).

Checks every page of the static site against the rules that were once broken
and must never break again:

  titles      unique across the site, non-empty, < 65 characters
  metas       description present, unique, 120-165 characters
  h1          exactly one per page
  canonical   present, absolute, on-domain
  links       no broken internal link (href/src)
  schema      every JSON-LD block parses; no aggregateRating anywhere;
              at most one FAQPage per page; FAQPage content must match the
              visible Q/A text exactly (generated by build-faq-schema.py)
  preloads    any <link rel=preload as=image> must reference an image the
              page (or the site CSS) actually uses
  css         exactly one styles.css reference, as a plain blocking link
  images      every <img> has width+height; files exist
  sitemap     parity with the indexable pages on disk
  nap         constants (email, phone, geo) present where expected; the old
              forbidden values are absent everywhere

Exit code: 0 = clean (warnings allowed unless --strict), 1 = errors.
Usage: python scripts/seo-qa.py [--strict]
"""
import glob
import json
import os
import re
import sys
from urllib.parse import unquote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
faqlib = __import__('build-faq-schema')

DOMAIN = 'https://stp-terrassement.com'
EMAIL = 'stp13109@gmail.com'
PHONE = '+33745142049'
GEO = '43.4302;5.4341'
NOINDEX_PAGES = {'404.html', 'avis.html', 'v38cnl93ujw3zgpz916ykx807t2c3v.html'}
FORBIDDEN = ['43.529742', '5.447427', '127 avis', 'contact@stp-terrassement.com',
             '4.9/5', '4,9/5', 'aggregateRating']

LD_RE = re.compile(r'<script type="application/ld\+json">(.*?)</script>', re.S)
LINK_RE = re.compile(r'(?:href|src)="([^"#]+)')
IMG_RE = re.compile(r'<img\b[^>]*>')
PRELOAD_IMG_RE = re.compile(r'<link rel="preload"[^>]*as="image"[^>]*>')

errors, warnings = [], []


def err(msg):
    errors.append(msg)


def warn(msg):
    warnings.append(msg)


def site_css_urls():
    urls = set()
    for css in glob.glob('css/*.css'):
        for m in re.finditer(r'url\([\'"]?([^\'")]+)', open(css, encoding='utf-8').read()):
            urls.add(os.path.normpath(os.path.join('css', m.group(1))).replace('\\', '/'))
    return urls


def main():
    strict = '--strict' in sys.argv
    os.chdir(ROOT)
    files = sorted(glob.glob('*.html') + glob.glob('blog/*.html'))
    css_assets = site_css_urls()
    titles, descs = {}, {}

    for f in files:
        fn = f.replace('\\', '/')
        t = open(f, encoding='utf-8').read()
        base = os.path.dirname(f)
        skip_page = os.path.basename(f) in NOINDEX_PAGES

        # document must start with the doctype (a script once inserted a <figure> before <head>)
        if os.path.basename(f) not in NOINDEX_PAGES and not t.lstrip().startswith('<!DOCTYPE html>'):
            err(f'{fn}: document must start with <!DOCTYPE html>')

        # forbidden legacy values — everywhere, even noindex pages
        for p in FORBIDDEN:
            if p in t:
                err(f'{fn}: forbidden value "{p}"')

        # broken internal links — everywhere
        for href in LINK_RE.findall(t):
            if href.startswith(('http', 'mailto:', 'tel:', 'data:', '//', 'javascript:')):
                continue
            path = unquote(href.split('?')[0])
            if not path:
                continue
            target = path.lstrip('/') if path.startswith('/') else \
                os.path.normpath(os.path.join(base, path)).replace('\\', '/')
            if target in ('', '.'):
                continue
            if not os.path.exists(target):
                err(f'{fn}: broken internal link -> {href}')

        # JSON-LD parses — everywhere
        faq_blocks = []
        for i, m in enumerate(LD_RE.finditer(t)):
            try:
                d = json.loads(m.group(1))
            except Exception as e:
                err(f'{fn}: JSON-LD block {i} invalid: {e}')
                continue
            if isinstance(d, dict) and d.get('@type') == 'FAQPage':
                faq_blocks.append(d)

        if skip_page:
            continue

        # title
        m = re.search(r'<title>(.*?)</title>', t, re.S)
        title = m.group(1).strip() if m else ''
        if not title:
            err(f'{fn}: missing <title>')
        elif len(title) >= 65:
            err(f'{fn}: title too long ({len(title)} chars)')
        if title in titles:
            err(f'{fn}: duplicate title (also on {titles[title]})')
        titles[title] = fn

        # meta description
        md = re.search(r'<meta name="description" content="([^"]*)"', t)
        if not md:
            err(f'{fn}: missing meta description')
        else:
            d = md.group(1)
            if not (120 <= len(d) <= 160):
                err(f'{fn}: meta description length {len(d)} (want 120-160)')
            if d in descs:
                err(f'{fn}: duplicate meta description (also on {descs[d]})')
            descs[d] = fn

        # exactly one h1
        n_h1 = len(re.findall(r'<h1\b', t))
        if n_h1 != 1:
            err(f'{fn}: {n_h1} <h1> tags (want exactly 1)')

        # canonical
        cm = re.search(r'<link rel="canonical" href="([^"]+)"', t)
        if not cm:
            err(f'{fn}: missing canonical')
        elif not cm.group(1).startswith(DOMAIN):
            err(f'{fn}: canonical off-domain: {cm.group(1)}')

        # FAQPage: at most one, exact parity with visible text
        if len(faq_blocks) > 1:
            err(f'{fn}: {len(faq_blocks)} FAQPage blocks (max 1)')
        elif faq_blocks:
            visible = {faqlib.norm(q): a for q, a in faqlib.extract_pairs(t)}
            for ent in faq_blocks[0].get('mainEntity', []):
                key = faqlib.norm(ent.get('name', ''))
                if key not in visible:
                    err(f'{fn}: FAQ question not in visible text: "{ent.get("name", "")[:60]}"')
                elif visible[key] != ent.get('acceptedAnswer', {}).get('text'):
                    err(f'{fn}: FAQ answer differs from visible text: "{ent.get("name", "")[:60]}"')

        # image preloads: only for images the page shows in an <img> tag.
        # Preloading a CSS background (the old hero preload) was measured to
        # cost ~1s of LCP because the LCP element is the hero text — banned.
        page_img_srcs = {os.path.basename(re.search(r'src="([^"]+)"', tag).group(1))
                         for tag in IMG_RE.findall(t)
                         if re.search(r'src="([^"]+)"', tag)}
        for tag in PRELOAD_IMG_RE.findall(t):
            hm = re.search(r'href="([^"]+)"', tag)
            if not hm:
                continue
            url = hm.group(1)
            fname = os.path.basename(url.split('?')[0])
            target = url.lstrip('/') if url.startswith('/') else \
                os.path.normpath(os.path.join(base, url)).replace('\\', '/')
            if fname in page_img_srcs:
                continue
            if target in css_assets:
                err(f'{fn}: preload of a CSS background image (measured LCP-negative): {url}')
            else:
                err(f'{fn}: preloaded image not used by the page: {url}')

        # css strategy — one pattern on every template page:
        # inline critical CSS + async styles.css (preload+onload + noscript
        # fallback, no plain blocking link)
        n_noscript = len(re.findall(r'<noscript><link rel="stylesheet" href="(?:\.\./)?css/styles\.css">', t))
        n_block = len(re.findall(r'<link rel="stylesheet" href="(?:\.\./)?css/styles\.css">', t)) - n_noscript
        n_async = len(re.findall(r'<link rel="preload" href="(?:\.\./)?css/styles\.css" as="style" onload=', t))
        has_critical = 'critical:start' in t
        if 'class="navbar"' in t:
            if not (has_critical and n_async == 1 and n_noscript == 1 and n_block == 0):
                err(f'{fn}: template page must use critical CSS + async styles.css '
                    f'(critical={has_critical}, async={n_async}, noscript={n_noscript}, blocking={n_block})')
            elif has_critical:
                # the critical block must carry the responsive breakpoints:
                # a parser bug once dropped 5 of 6 @media rules and shipped a
                # first-frame reflow (prod CLS 0.42-0.55 on hero pages)
                cm = re.search(r'<!-- critical:start -->(.*?)<!-- critical:end -->', t, re.S)
                cblock = cm.group(1) if cm else ''
                if cblock.count('@media') < 4 or 'max-width:768px' not in cblock:
                    err(f'{fn}: critical CSS block missing responsive breakpoints '
                        f'(@media={cblock.count("@media")})')
            if not re.search(r'"@type":\s*"WebSite"', t):
                err(f'{fn}: missing WebSite schema')

        # schema completeness (SEO check 2026-09-03): og:image dimensions, Service
        # identity, LocalBusiness geo/map/hours, page-type entity, clean FAQ answers
        for og_key in ('og:image:width', 'og:image:height', 'og:image:alt'):
            if f'property="{og_key}"' not in t:
                err(f'{fn}: missing {og_key}')
        lds = []
        for m in LD_RE.finditer(t):
            try:
                lds.append(json.loads(m.group(1)))
            except Exception:
                pass

        def walk(node):
            if isinstance(node, dict):
                yield node
                for v in node.values():
                    yield from walk(v)
            elif isinstance(node, list):
                for v in node:
                    yield from walk(v)
        ORG_ID = DOMAIN + '/#organization'
        for node in [n for d in lds for n in walk(d)]:
            if node.get('@type') == 'Service' and node.get('serviceType') and 'provider' in node:
                for key in ('@id', 'name', 'url'):
                    if not node.get(key):
                        err(f'{fn}: Service schema missing {key}')
            if node.get('@id') == ORG_ID and 'name' in node and 'address' in node:
                for key in ('geo', 'hasMap', 'openingHoursSpecification'):
                    if key not in node:
                        err(f'{fn}: LocalBusiness node missing {key}')
        ENTITY_TYPES = {'Service', 'Article', 'WebPage', 'CollectionPage', 'ContactPage',
                        'DefinedTermSet', 'LocalBusiness', 'ItemList', 'AboutPage'}
        top_types = set()
        for d in lds:
            ty = d.get('@type') if isinstance(d, dict) else None
            for x in (ty if isinstance(ty, list) else [ty]):
                top_types.add(x)
            if isinstance(d, dict) and '@graph' in d:
                for g in d['@graph']:
                    top_types.add(g.get('@type'))
        if not top_types & ENTITY_TYPES:
            err(f'{fn}: no page-type schema (one of {sorted(ENTITY_TYPES)})')
        for fb in faq_blocks:
            for ent in fb.get('mainEntity', []):
                a = ent.get('acceptedAnswer', {}).get('text', '')
                if 'Devis gratuit sous 24 h' in a or 'Faire analyser mon devis' in a:
                    err(f'{fn}: FAQ answer polluted by cta-local text: "{ent.get("name", "")[:50]}"')

        # first-frame accessibility: focus ring + reduced-motion must ship inline (audit tools only
        # read inline CSS; keyboard users and vestibular users must not wait for styles.css)
        if 'focus-visible' not in t:
            err(f'{fn}: :focus-visible rule missing from the inline critical block')
        if 'prefers-reduced-motion' not in t:
            err(f'{fn}: prefers-reduced-motion block missing from the inline critical block')
        if 'font-display:block' in t:
            err(f'{fn}: font-display:block found (use fallback/swap)')

        # spec SEO-07 / SEO-01: mobile call bar and conversion tracking on every template page
        if 'class="callbar"' not in t:
            err(f'{fn}: mobile call bar (.callbar) missing')
        if 'js/track.js' not in t:
            err(f'{fn}: js/track.js not loaded')

        # GitHub-Pages-only hardening: full meta CSP + frame-buster
        if 'content="default-src' not in t:
            err(f'{fn}: missing full Content-Security-Policy meta')
        if 'self!==top' not in t:
            err(f'{fn}: missing frame-buster snippet')

        # hreflang self + x-default (single-language site, documented intent)
        if 'hreflang="fr"' not in t or 'hreflang="x-default"' not in t:
            err(f'{fn}: missing hreflang fr/x-default pair')

        # noindex is only allowed on the utility pages excluded above
        if re.search(r'<meta name="robots" content="[^"]*noindex', t):
            err(f'{fn}: unexpected noindex directive')

        # images: dimensions + files exist
        for tag in IMG_RE.findall(t):
            sm = re.search(r'src="([^"]+)"', tag)
            src = sm.group(1) if sm else ''
            if 'width=' not in tag or 'height=' not in tag:
                err(f'{fn}: <img> without width/height: {src[:60]}')
            if src and not src.startswith(('http', 'data:')):
                p = src.lstrip('/') if src.startswith('/') else \
                    os.path.normpath(os.path.join(base, src)).replace('\\', '/')
                if not os.path.exists(p):
                    err(f'{fn}: <img> file missing: {src}')

        # NAP presence on template pages (footer)
        if 'stp13109' not in t:
            warn(f'{fn}: contact email not referenced')

        # accessibility / audit invariants
        if '<main' not in t:
            err(f'{fn}: no <main> landmark')
        prev = 0
        for hm in re.finditer(r'<h([1-6])\b', t):
            lvl = int(hm.group(1))
            if prev and lvl > prev + 1:
                err(f'{fn}: heading level skip h{prev}->h{lvl}')
                break
            prev = lvl
        if 'href="index.html"' in t or 'href="../index.html"' in t:
            err(f'{fn}: internal link to index.html (use href="/" - avoids the '
                f'/ vs /index.html duplicate-URL surface)')
        if 'href="#"' in t:
            err(f'{fn}: placeholder href="#" link')
        if 'class="navbar"' in t:
            if 'skip-link' not in t:
                err(f'{fn}: missing skip-to-content link')
            if 'id="main-content"' not in t:
                err(f'{fn}: missing id="main-content" skip target')
        # icons: self-hosted Font Awesome subset (no third-party CSS/fonts), both faces preloaded
        if 'cdnjs.cloudflare.com/ajax' in t:
            err(f'{fn}: Font Awesome still loaded from cdnjs (must use the self-hosted subset)')
        for face in ('fa-solid-subset.woff2', 'fa-brands-subset.woff2'):
            if f'<link rel="preload" href="/fonts/{face}"' not in t:
                err(f'{fn}: missing preload for /fonts/{face}')
        # Article schema must carry an image (rich results recommendation)
        for m2 in LD_RE.finditer(t):
            try:
                d2 = json.loads(m2.group(1))
            except Exception:
                continue
            if isinstance(d2, dict) and d2.get('@type') == 'Article' and 'image' not in d2:
                err(f'{fn}: Article schema without image property')

    # sitemap parity
    sm = open('sitemap.xml', encoding='utf-8').read()
    locs = re.findall(r'<loc>([^<]+)</loc>', sm)
    if len(locs) != len(set(locs)):
        err('sitemap.xml: duplicate <loc> entries')
    sm_paths = {(u.replace(DOMAIN + '/', '') or 'index.html') for u in locs}
    disk = {f.replace('\\', '/') for f in files} - NOINDEX_PAGES
    for missing in sorted(disk - sm_paths):
        err(f'sitemap.xml: page on disk but not in sitemap: {missing}')
    for ghost in sorted(sm_paths - disk):
        err(f'sitemap.xml: entry without file (or excluded page): {ghost}')

    # focus indicators must stay visible (a11y)
    css = open('css/styles.css', encoding='utf-8').read()
    if re.search(r'outline\s*:\s*(none|0)\b', css):
        err('css/styles.css: outline removed without visible replacement')
    if ':focus-visible' not in css:
        err('css/styles.css: missing :focus-visible rules')

    # NAP constants in the org schema (homepage)
    home = open('index.html', encoding='utf-8').read()
    for needle, label in [(EMAIL, 'email'), (PHONE, 'phone'), ('798 C Chemin de la Roque', 'street')]:
        if needle not in home:
            err(f'index.html: NAP constant missing: {label}')
    if GEO not in home:
        err('index.html: geo.position meta does not match constants')

    print(f'seo-qa: {len(files)} pages checked')
    for e in errors:
        print('ERROR  ', e)
    shown = warnings if strict else warnings[:20]
    for w in shown:
        print('warn   ', w)
    print(f'seo-qa: {len(errors)} errors, {len(warnings)} warnings'
          + (' [strict]' if strict else ''))
    if errors or (strict and warnings):
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
