#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""SEO QA — anti-regression suite for stp-terrassement.com (SEO spec v2, T-40).

Checks every page of the static site against the rules that were once broken
and must never break again:

  titles      unique across the site, non-empty, < 65 characters
  metas       description present, unique, 120-165 characters
  h1          exactly one per page
  canonical   present, absolute, on-domain
  links       no broken internal link (href/src)
  schema      every JSON-LD block parses; no aggregateRating anywhere;
              at most one FAQPage per page; FAQPage content must match the
              visible Q/A text exactly (generated by build-faq-schema.py)
  preloads    any <link rel=preload as=image> must reference an image the
              page (or the site CSS) actually uses
  css         exactly one styles.css reference, as a plain blocking link
  images      every <img> has width+height; files exist
  sitemap     parity with the indexable pages on disk
  nap         constants (email, phone, geo) present where expected; the old
              forbidden values are absent everywhere

Exit code: 0 = clean (warnings allowed unless --strict), 1 = errors.
Usage: python scripts/seo-qa.py [--strict]
"""
import glob
import json
import os
import re
import sys
from urllib.parse import unquote

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
faqlib = __import__('build-faq-schema')

DOMAIN = 'https://stp-terrassement.com'
EMAIL = 'stp13109@gmail.com'
PHONE = '+33745142049'
GEO = '43.4302;5.4341'
NOINDEX_PAGES = {'404.html', 'avis.html', 'v38cnl93ujw3zgpz916ykx807t2c3v.html'}
FORBIDDEN = ['43.529742', '5.447427', '127 avis', 'contact@stp-terrassement.com',
             '4.9/5', '4,9/5', 'aggregateRating']

LD_RE = re.compile(r'<script type="application/ld\+json">(.*?)</script>', re.S)
LINK_RE = re.compile(r'(?:href|src)="([^"#]+)')
IMG_RE = re.compile(r'<img\b[^>]*>')
PRELOAD_IMG_RE = re.compile(r'<link rel="preload"[^>]*as="image"[^>]*>')

errors, warnings = [], []


def err(msg):
    errors.append(msg)


def warn(msg):
    warnings.append(msg)


def site_css_urls():
    urls = set()
    for css in glob.glob('css/*.css'):
        for m in re.finditer(r'url\([\'"]?([^\'")]+)', open(css, encoding='utf-8').read()):
            urls.add(os.path.normpath(os.path.join('css', m.group(1))).replace('\\', '/'))
    return urls


def main():
    strict = '--strict' in sys.argv
    os.chdir(ROOT)
    files = sorted(glob.glob('*.html') + glob.glob('blog/*.html'))
    css_assets = site_css_urls()
    titles, descs = {}, {}

    for f in files:
        fn = f.replace('\\', '/')
        t = open(f, encoding='utf-8').read()
        base = os.path.dirname(f)
        skip_page = os.path.basename(f) in NOINDEX_PAGES

        # forbidden legacy values — everywhere, even noindex pages
        for p in FORBIDDEN:
            if p in t:
                err(f'{fn}: forbidden value "{p}"')

        # broken internal links — everywhere
        for href in LINK_RE.findall(t):
            if href.startswith(('http', 'mailto:', 'tel:', 'data:', '//', 'javascript:')):
                continue
            path = unquote(href.split('?')[0])
            if not path:
                continue
            target = path.lstrip('/') if path.startswith('/') else \
                os.path.normpath(os.path.join(base, path)).replace('\\', '/')
            if target in ('', '.'):
                continue
            if not os.path.exists(target):
                err(f'{fn}: broken internal link -> {href}')

        # JSON-LD parses — everywhere
        faq_blocks = []
        for i, m in enumerate(LD_RE.finditer(t)):
            try:
                d = json.loads(m.group(1))
            except Exception as e:
                err(f'{fn}: JSON-LD block {i} invalid: {e}')
                continue
            if isinstance(d, dict) and d.get('@type') == 'FAQPage':
                faq_blocks.append(d)

        if skip_page:
            continue

        # title
        m = re.search(r'<title>(.*?)</title>', t, re.S)
        title = m.group(1).strip() if m else ''
        if not title:
            err(f'{fn}: missing <title>')
        elif len(title) >= 65:
            err(f'{fn}: title too long ({len(title)} chars)')
        if title in titles:
            err(f'{fn}: duplicate title (also on {titles[title]})')
        titles[title] = fn

        # meta description
        md = re.search(r'<meta name="description" content="([^"]*)"', t)
        if not md:
            err(f'{fn}: missing meta description')
        else:
            d = md.group(1)
            if not (120 <= len(d) <= 165):
                err(f'{fn}: meta description length {len(d)} (want 120-165)')
            if d in descs:
                err(f'{fn}: duplicate meta description (also on {descs[d]})')
            descs[d] = fn

        # exactly one h1
        n_h1 = len(re.findall(r'<h1\b', t))
        if n_h1 != 1:
            err(f'{fn}: {n_h1} <h1> tags (want exactly 1)')

        # canonical
        cm = re.search(r'<link rel="canonical" href="([^"]+)"', t)
        if not cm:
            err(f'{fn}: missing canonical')
        elif not cm.group(1).startswith(DOMAIN):
            err(f'{fn}: canonical off-domain: {cm.group(1)}')

        # FAQPage: at most one, exact parity with visible text
        if len(faq_blocks) > 1:
            err(f'{fn}: {len(faq_blocks)} FAQPage blocks (max 1)')
        elif faq_blocks:
            visible = {faqlib.norm(q): a for q, a in faqlib.extract_pairs(t)}
            for ent in faq_blocks[0].get('mainEntity', []):
                key = faqlib.norm(ent.get('name', ''))
                if key not in visible:
                    err(f'{fn}: FAQ question not in visible text: "{ent.get("name", "")[:60]}"')
                elif visible[key] != ent.get('acceptedAnswer', {}).get('text'):
                    err(f'{fn}: FAQ answer differs from visible text: "{ent.get("name", "")[:60]}"')

        # image preloads: only for images the page shows in an <img> tag.
        # Preloading a CSS background (the old hero preload) was measured to
        # cost ~1s of LCP because the LCP element is the hero text — banned.
        page_img_srcs = {os.path.basename(re.search(r'src="([^"]+)"', tag).group(1))
                         for tag in IMG_RE.findall(t)
                         if re.search(r'src="([^"]+)"', tag)}
        for tag in PRELOAD_IMG_RE.findall(t):
            hm = re.search(r'href="([^"]+)"', tag)
            if not hm:
                continue
            url = hm.group(1)
            fname = os.path.basename(url.split('?')[0])
            target = url.lstrip('/') if url.startswith('/') else \
                os.path.normpath(os.path.join(base, url)).replace('\\', '/')
            if fname in page_img_srcs:
                continue
            if target in css_assets:
                err(f'{fn}: preload of a CSS background image (measured LCP-negative): {url}')
            else:
                err(f'{fn}: preloaded image not used by the page: {url}')

        # css strategy: exactly one plain blocking styles.css link
        n_block = len(re.findall(r'<link rel="stylesheet" href="(?:\.\./)?css/styles\.css">', t))
        n_any = t.count('styles.css')
        if n_block != 1 or n_any != 1:
            err(f'{fn}: styles.css strategy wrong (blocking={n_block}, refs={n_any}; want 1/1)')

        # images: dimensions + files exist
        for tag in IMG_RE.findall(t):
            sm = re.search(r'src="([^"]+)"', tag)
            src = sm.group(1) if sm else ''
            if 'width=' not in tag or 'height=' not in tag:
                err(f'{fn}: <img> without width/height: {src[:60]}')
            if src and not src.startswith(('http', 'data:')):
                p = src.lstrip('/') if src.startswith('/') else \
                    os.path.normpath(os.path.join(base, src)).replace('\\', '/')
                if not os.path.exists(p):
                    err(f'{fn}: <img> file missing: {src}')

        # NAP presence on template pages (footer)
        if 'stp13109' not in t:
            warn(f'{fn}: contact email not referenced')

        # accessibility / audit invariants
        if '<main' not in t:
            err(f'{fn}: no <main> landmark')
        if 'href="#"' in t:
            err(f'{fn}: placeholder href="#" link')
        if 'class="navbar"' in t:
            if 'skip-link' not in t:
                err(f'{fn}: missing skip-to-content link')
            if 'id="main-content"' not in t:
                err(f'{fn}: missing id="main-content" skip target')
        if 'font-awesome/6.5.1/css/all.min.css"' in t and 'integrity="sha384-' not in t:
            err(f'{fn}: Font Awesome CSS without SRI integrity')
        # Article schema must carry an image (rich results recommendation)
        for m2 in LD_RE.finditer(t):
            try:
                d2 = json.loads(m2.group(1))
            except Exception:
                continue
            if isinstance(d2, dict) and d2.get('@type') == 'Article' and 'image' not in d2:
                err(f'{fn}: Article schema without image property')

    # sitemap parity
    sm = open('sitemap.xml', encoding='utf-8').read()
    locs = re.findall(r'<loc>([^<]+)</loc>', sm)
    if len(locs) != len(set(locs)):
        err('sitemap.xml: duplicate <loc> entries')
    sm_paths = {(u.replace(DOMAIN + '/', '') or 'index.html') for u in locs}
    disk = {f.replace('\\', '/') for f in files} - {
        'mentions-legales.html', 'politique-confidentialite.html'} - NOINDEX_PAGES
    for missing in sorted(disk - sm_paths):
        err(f'sitemap.xml: page on disk but not in sitemap: {missing}')
    for ghost in sorted(sm_paths - disk):
        err(f'sitemap.xml: entry without file (or excluded page): {ghost}')

    # NAP constants in the org schema (homepage)
    home = open('index.html', encoding='utf-8').read()
    for needle, label in [(EMAIL, 'email'), (PHONE, 'phone'), ('798 C Chemin de la Roque', 'street')]:
        if needle not in home:
            err(f'index.html: NAP constant missing: {label}')
    if GEO not in home:
        err('index.html: geo.position meta does not match constants')

    print(f'seo-qa: {len(files)} pages checked')
    for e in errors:
        print('ERROR  ', e)
    shown = warnings if strict else warnings[:20]
    for w in shown:
        print('warn   ', w)
    print(f'seo-qa: {len(errors)} errors, {len(warnings)} warnings'
          + (' [strict]' if strict else ''))
    if errors or (strict and warnings):
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
